package com.fund.manageFunds.domain.model;

import lombok.Getter;
import lombok.Setter;
import software.amazon.awssdk.enhanced.dynamodb.Key;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.LocalDateTime;

@DynamoDbBean
public class Subscription {
    @Setter
    private String id;
    @Setter
    private String clientEmail;
    @Setter
    @Getter
    private String fundName;
    @Setter
    @Getter
    private SubscriptionState state;
    @Setter
    @Getter
    private Double initialAmount;
    @Setter
    @Getter
    private Double investAmount;
    @Setter
    @Getter
    private Double residualAMount;
    @Getter
    @Setter
    private String date;
    @Getter
    @Setter
    private NotificationOptions notificationOption;
    @Getter
    @Setter
    private String informationForNotification;

    @DynamoDbSortKey
    public String getId() {
        return id;
    }

    @DynamoDbPartitionKey
    public String getClientEmail() {
        return clientEmail;
    }

    public Key getHashKey(String clientEmailValue, String idValue){
        return Key.builder()
                .partitionValue(clientEmailValue)
                .sortValue(idValue)
                .build();
    }
}
